# pylint: disable=no-member,invalid-name,line-too-long,trailing-whitespace
"""Initial database definition

Revision ID: 93b6e6de2af0
Revises: 
Create Date: 2020-11-05 17:13:43.216312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b6e6de2af0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CompanyBASE',
                    sa.Column('Symbol', sa.String(length=10), nullable=False),
                    sa.Column('Name', sa.String(length=128), nullable=True),
                    sa.Column('Market', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('Symbol')
                    )
    op.create_table('ConfigurationBASE',
                    sa.Column('Id', sa.Integer(), nullable=False),
                    sa.Column('Name', sa.String(length=128), nullable=False),
                    sa.Column('Type', sa.String(length=50), nullable=False),
                    sa.Column('ValueTXT', sa.String(
                        length=255), nullable=True),
                    sa.Column('ValueNBR', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('Id')
                    )
    op.create_table('HandlerBASE',
                    sa.Column('HandlerID', sa.Integer(), nullable=False),
                    sa.Column('Name', sa.String(length=128), nullable=False),
                    sa.PrimaryKeyConstraint('HandlerID')
                    )
    op.create_table('FeatureBASE',
                    sa.Column('Name', sa.String(length=50), nullable=False),
                    sa.Column('URI', sa.String(length=255), nullable=False),
                    sa.Column('HandlerID', sa.Integer(), nullable=True),
                    sa.Column('Description', sa.String(
                        length=255), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['HandlerID'], ['HandlerBASE.HandlerID'], ),
                    sa.PrimaryKeyConstraint('Name')
                    )
    op.create_table('CompanyFeatureBASE',
                    sa.Column('CompanyFeatureID',
                              sa.Integer(), nullable=False, primary_key=True),
                    sa.Column('FeatureName', sa.String(
                        length=50), nullable=False),
                    sa.Column('CompanySymbol', sa.String(
                        length=50), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['CompanySymbol'], ['CompanyBASE.Symbol'], ),
                    sa.ForeignKeyConstraint(
                        ['FeatureName'], ['FeatureBASE.Name'], )
                    )
    op.create_table('StatisticsBASE',
                    sa.Column('CompanySymbol', sa.String(
                        length=10), nullable=False),
                    sa.Column('FeatureName', sa.String(
                        length=50), nullable=False),
                    sa.Column('RetrievalDTS', sa.DateTime(), nullable=False),
                    sa.Column('RowCount', sa.Integer(),
                              nullable=True, default=0),
                    sa.ForeignKeyConstraint(
                        ['CompanySymbol'], ['CompanyBASE.Symbol'], ),
                    sa.ForeignKeyConstraint(
                        ['FeatureName'], ['FeatureBASE.Name'], ),
                    sa.PrimaryKeyConstraint(
                        'CompanySymbol', 'FeatureName', 'RetrievalDTS')
                    )
    op.create_table('OptionBASE',
                    sa.Column('Name', sa.String(length=50), nullable=False),
                    sa.Column('CompanySymbol', sa.String(
                        length=50), nullable=False),
                    sa.Column('FeatureName', sa.String(
                        length=50), nullable=False),
                    sa.Column('Type', sa.String(length=50), nullable=False),
                    sa.Column('ValueTXT', sa.String(
                        length=255), nullable=True),
                    sa.Column('ValueNBR', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['CompanySymbol'], ['CompanyFeatureBASE.CompanySymbol'], ),
                    sa.ForeignKeyConstraint(
                        ['FeatureName'], ['CompanyFeatureBASE.FeatureName'], ),
                    sa.PrimaryKeyConstraint(
                        'Name', 'CompanySymbol', 'FeatureName')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OptionBASE')
    op.drop_table('StatisticsBASE')
    op.drop_table('CompanyFeatureBASE')
    op.drop_table('FeatureBASE')
    op.drop_table('HandlerBASE')
    op.drop_table('ConfigurationBASE')
    op.drop_table('CompanyBASE')
    # ### end Alembic commands ###
